version: "3.0"

services:

  nginx:
    container_name: nginx
    image: nginx:1-alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  ghost:
    container_name: ghost
    image: ghost:5-alpine
    volumes:
      - ghost:/var/lib/ghost/content
    environment:
      NODE_ENV: development
      url: https://localhost
      database__client: sqlite3
      database__connection__filename: "content/data/ghost.db"
      database__useNullAsDefault: true
      database__debug: false

volumes:

  ghost:
    name: ghost